---
- name: ensure rhel 7
  when: not (ansible_os_family == "RedHat" and ansible_distribution_major_version == "7")
  fail:
    msg: "Host must be rhel 7"

- name: ensure tcp_bbr module present
  modprobe:
    name: tcp_bbr

- name: load tcp_bbr module on boot next time
  copy:
    src: tcp_bbr.conf
    dest: /etc/modules-load.d/tcp_bbr.conf

- name: extra sysctl conf
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - {"name": "net.core.default_qdisc", "value": "fq"}
    - {"name": "net.ipv4.tcp_congestion_control", "value": "bbr"}
  ignore_errors: true
...
