---
- name: install package
  yum:
    name: redis

- name: apply config files
  template:
    src: redis.conf
    dest: /etc/redis/redis.conf
  notify:
    - restart redis

- name: enable and start redis
  service:
    name: redis
    enabled: yes
    state: started
...
