---
- name: openldap client config for rhel7
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == 7
  include_tasks: client-rhel7.yml

- name: openldap client config for debian
  when: ansible_os_family == "Debian"
  include_tasks: client-debian.yml
...
