---
- name: save iptables(rhel7)
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  shell: service iptables save

- name: save iptables(debian)
  when: ansible_os_family == "Debian"
  shell: netfilter-persistent save

- name: restart iptables(rhel7)
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  systemd:
    name: iptables
    state: restarted

- name: restart iptables(debian)
  when: ansible_os_family == "Debian"
  systemd:
    name: netfilter-persistent
    state: restarted

- name: restart iptables-one
  systemd:
    name: iptables-one.service
    state: restarted

- name: systemd daemon reload
  systemd:
    daemon_reload: yes
...
