---
dependencies: []

galaxy_info:
  author: major1201
  description: nfs-client
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 6
        - 7
  galaxy_tags:
    - system
    - nfs-client
