---
- name: restart rsyncd rhel6
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == 6
  service:
    name: xinetd
    state: restarted

- name: restart rsyncd rhel7
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == 7
  service:
    name: rsyncd
    state: restarted
...
