---
- name: apply ceph repo in redhat
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  template:
    src: "{{ ceph_repo }}"
    dest: /etc/yum.repos.d/ceph.repo

- name: apt update in debian
  when: ansible_os_family == "Debian"
  apt:
    update_cache: yes

- name: install pkgs
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ceph-common

- name: apply config file
  template:
    src: "{{ ceph_conf }}"
    dest: /etc/ceph/ceph.conf

- name: apply client keys
  copy:
    src: "{{ item }}"
    dest: /etc/ceph/{{ item | basename }}
    owner: root
    group: root
    mode: 0600
  with_items: "{{ ceph_client_keyrings }}"

- name: rbdmap
  import_tasks: rbdmap.yml

- name: cephfs
  import_tasks: cephfs.yml
...
