---
- name: disable dns overwrite be NetworkManger on CentOS 7
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  copy:
    src: dns.conf
    dest: /etc/NetworkManager/conf.d/dns.conf
  notify:
    - restart network manager

- name: restart network manager now
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  meta: flush_handlers

- name: remove resolv.conf hard links
  file:
    dest: /etc/sysconfig/networking/profiles/default/resolv.conf
    state: absent

- name: set dns servers
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
...
