---
- name: install required softwares
  when: ansible_os_family == "RedHat"
  yum:
    name:
      - lrzsz
      - nethogs
      - net-tools
      - moreutils
      - vim-enhanced
      - tmux
      - tree
      - psmisc
      - openssl
      - openssl-static
      - openssl-devel
      - telnet
      - zlib
      - libtool
      - deltarpm
      - lshw
      - ack
      - bash-completion
      - zip
      - unzip
      - lftp
      - wget
      - yum-utils
      - conntrack-tools
    state: present
  async: 1000
  poll: 0
  register: yum_sleeper

- name: wait for installation
  when: ansible_os_family == "RedHat"
  async_status:
    jid: "{{ yum_sleeper.results[0].ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 100

- name: install required softwares centos6
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == 6
  yum:
    name:
      - iptraf
      - python-pip
    state: present

- name: install required softwares centos7
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == 7
  yum:
    name:
      - iptraf-ng
      - python2-pip
    state: present

- name: install required softwares debian
  when: ansible_os_family == "Debian"
  apt:
    name:
      - apt-transport-https
      - sudo
      - lrzsz
      - vim
      - tmux
      - tree
      - psmisc
      - telnet
      - zip
      - unzip
      - conntrack
      - lsof
...
