---
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
# api:
  # advertiseAddress: 192.168.57.11
  # bindPort: 6443
networking:
  podSubnet: 192.168.122.0/24
kubernetesVersion: v1.9.4
featureGates:
   CoreDNS: true
...
