---
- name: ensure rhel 7
  when: not (ansible_os_family == "RedHat" and ansible_distribution_major_version == 7)
  fail:
    msg: "Docker host must be rhel 7"

- name: install docker
  yum:
    name: docker

- name: ensure etc directory exists
  file:
    path: /etc/docker
    mode: 0755
    state: directory

- name: apply config file
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify:
    - restart docker

- name: add useful scripts
  copy:
    src: dockertags
    dest: /usr/bin/dockertags
    owner: root
    group: root
    mode: 0755

- name: enable and start docker
  service:
    name: docker
    enabled: yes
    state: started
...
